# Generated by Django 3.2.24 on 2024-02-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disability_aid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEnsion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=100)),
                ('retirement_Date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('PANCHAYAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disability_aid.panchayat')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disability_aid.user')),
            ],
        ),
    ]
