# Generated by Django 3.2.24 on 2024-02-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disability_aid', '0002_pension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pension',
            old_name='dept',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='pension',
            name='office',
        ),
        migrations.RemoveField(
            model_name='pension',
            name='retirement_Date',
        ),
    ]
