# Generated by Django 3.2.24 on 2024-02-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disability_aid', '0003_auto_20240227_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
