# Generated by Django 3.2.24 on 2024-03-07 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disability_aid', '0004_pension_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pension_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
                ('PENSION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disability_aid.pension')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('feedback', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disability_aid.user')),
            ],
        ),
    ]
