# Generated by Django 3.2.24 on 2024-03-27 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disability_aid', '0006_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='LOGIN',
        ),
        migrations.AddField(
            model_name='doctor',
            name='HOSPITAL',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='disability_aid.hospital'),
            preserve_default=False,
        ),
    ]
